version: '3.3'
services:
  web:
    build: .
    # ports:
    #   - 8080:3000
    
  nginx:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    